version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --requirepass 1234

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A main.celery_app worker --loglevel=info --concurrency=4 --pool=solo
    volumes:
      - .:/python
    depends_on:
      - redis

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis