FROM tensorflow/tensorflow:2.12.0-gpu

# Creo un directorio de trabajo
WORKDIR /proyecto

# Actualizo e instalo paquetes
RUN apt-get update && \
    apt-get install python3 && \
    apt-get install -y redis-server && \
    apt-get install -y ffmpeg git && \
    rm -rf /var/lib/apt/lists/*
